### ISSUE TITLE
AudioPlayer gets stuck after playing 22050Hz WAV generated by espeak

### ISSUE THREAD

**Issue by Moarc** [Nailik/rhasspy_mobile#157]
AudioPlayer gets stuck after playing 22kHz audio - any subsequent attempt to play audio result in `AudioPlayer playData already playing data`. Unfortunately, this samplerate is hardcoded in espeak, which makes it "impossible" to use espeak with this app.

**Comment by Nailik** [comment]
Thank you @Moarc for checking out the project. I am currently working on a major rework how the app internally works etc. Hopefully this will fix the issue. I hope the next release is within a month.

**Comment by Moarc** [comment]
Well then, good luck, smooth progress, and a happy New Year!

**Comment by Nailik** [comment]
Will be fixed in 0.4, using Android MediaPlayer(sound) or Ringtone Manager(notification) instead of Audio Track.

**Comment by Nailik** [comment]
Should be fixed with latest release, please comment if you have further issues.

**Comment by Moarc** [comment]
Fixed indeed.

Thank you. Honestly, I've tried everything I could find (Almond, Dicio, Mycroft…), and this is the first usable Free solution that I've encountered in this field - Rhasspy itself and your app specifically, since some other projects are pretty much usable on a standalone device, yet not on phones.

**Comment by Nailik** [comment]
Thank you, it was a hell lot of work. I hop rhasspy 3.0 will not break it.
You can now also download it from the playstore to get updates.
