### ISSUE TITLE
Issues getting app to work

### ISSUE THREAD

**Issue by mrchainman** [Nailik/rhasspy_mobile#163]
I have configured the app according to https://rhasspy.readthedocs.io/en/latest/tutorials/#server-with-satellites with a shared mqtt broker.
The app seems to have issues tough, all I see in the logs is "AudioPlayer playSound already playing data"

**Comment by Nailik** [comment]
Yes the AudioPlayer currently has some issues and is being reworked. Your issue should have the same reason as #157

**Comment by Nailik** [comment]
Should be fixed with latest release, please comment if you have further issues.
