### ISSUE TITLE
Voice feedback does not work

### ISSUE THREAD

**Issue by manducagiuseppe** [Nailik/rhasspy_mobile#293]
First of all, I would like to compliment you on creating the app. I have installed the app on my smartphone and everything is working correctly, the only problem is that the voice feedback of the assistant is not working. Why is that? How can I solve it?

**Comment by Nailik** [comment]
Can you please clarify what about the voice feedback is not working?

- Audio Playing settings in app.
- Audio Playing settings in your rhasspy base.
- How do you trigger voice feedback (do you use mqtt or http, do you send wav data to be played or do you send text to be spoken to the app?)
- Do you know if the voice feedback is generated and not played or are you not sure?

**Comment by manducagiuseppe** [comment]
Here is my configuration

-  Local - Audio Playing settings in app 
-  Remote HTTP - Audio Playing settings rhasspy base
-  If I write from the Rhasspy base, the voice is correctly reproduced on the satellite device, but if I ask the satellite device, for example, 'Turn on the light,' the command works but I don't hear the response, for example, 'The light has been turned on.

My App Configuration:

- Speech to Text : Remote Http 
- Intent Recognition: Remote Http
- Text to Speech: Remote Http
- Audio Playing: Local
- Dialog Management: Local

My Rhasspy Base configuration
<pre>
{
    "dialogue": {
        "satellite_site_ids": "mobile",
        "system": "rhasspy"
    },
    "handle": {
        "satellite_site_ids": "mobile",
        "system": "hass"
    },
    "home_assistant": {
        "access_token": "*********",
        "url": "http://192.168.1.254:8123"
    },
    "intent": {
        "remote": {
            "url": "http://192.168.1.254:12101/api/text-to-intent"
        },
        "satellite_site_ids": "mobile",
        "system": "fsticuffs"
    },
    "microphone": {
        "pyaudio": {
            "siteId": "mobile",
            "udp_audio_host": "192.168.1.123",
            "udp_audio_port": "12202"
        },
        "system": "pyaudio"
    },
    "mqtt": {
        "enabled": "",
        "host": "192.168.1.254",
        "password": "*****",
        "username": "*****"
    },
    "sounds": {
        "aplay": {
            "device": "default"
        },
        "remote": {
            "url": "http://192.168.1.123:12101/api/play-wav"
        },
        "system": "remote"
    },
    "speech_to_text": {
        "remote": {
            "url": "http://192.168.1.254:12101/api/speech-to-text"
        },
        "satellite_site_ids": "mobile",
        "system": "kaldi"
    },
    "text_to_speech": {
        "remote": {
            "url": "http://192.168.1.123:12101/api/text-to-speech"
        },
        "satellite_site_ids": "mobile",
        "system": "nanotts"
    },
    "wake": {
        "porcupine": {
            "keyword_path": "porcupine_linux.ppn",
            "udp_audio": "12202"
        },
        "satellite_site_ids": "mobile"
    }
}
</pre>

**Comment by Nailik** [comment]
How do you trigger your text-to-speech service?

**Comment by Nailik** [comment]
Should be fixed with the newest release [V_0.5](https://github.com/Nailik/rhasspy_mobile/releases/tag/V_0.5.0-102).
You can consolidate newly updated [Wiki](https://github.com/Nailik/rhasspy_mobile/wiki) for more help.

Mqtt now also supports say endpoint.

Please comment when there are still any issues.
