### ISSUE TITLE
Sometimes app stucks on loading indicator after saying command

### ISSUE THREAD

**Issue by wiiiteek** [Nailik/rhasspy_mobile#297]
Hello,

App sometime hangs after saying command and I have to manulally force stop application in Android settings. Whole time loading indicator spins and I application is not listening for other commands.

I'am using version 0.4.9-66, here is log file [rhasspy_logfile_2023-03-11T09_30_00.968.txt](https://github.com/Nailik/rhasspy_mobile/files/10948140/rhasspy_logfile_2023-03-11T09_30_00.968.txt)

**Comment by Nailik** [comment]
Currently i can't see an issue in the log - can you tell me what device you are using and which Android version as well?

**Comment by wiiiteek** [comment]
Yeah sure,
I am using Doogee S58Pro with Android 10

here is screenshot how it looks when app stuck
![Screenshot_20230311-102723](https://user-images.githubusercontent.com/11781536/224566488-c3d0a0f5-3fcf-4ffe-9149-a7a9a64e2ec6.png)

**Comment by Nailik** [comment]
Can you still interact with the ui after the indicator is stuck?

**Comment by wiiiteek** [comment]
Yes I can. I can change tabs, show settings, etc. This indicator is showing even if I leave app.
The only thing which is blocked is recording. This big button with microphone at home tab seems to be disabled and wake work does not work.

**Comment by Nailik** [comment]
Is the command executed?
What do you use for speech-to-text ? (mqtt?)
Do you have your client added to Dialog Managment in your rhasspy server?

**Comment by Nailik** [comment]
Should be fixed with the newest release [V_0.5](https://github.com/Nailik/rhasspy_mobile/releases/tag/V_0.5.0-102).
You can consolidate newly updated [Wiki](https://github.com/Nailik/rhasspy_mobile/wiki) for more help.

Please comment when there are still any issues.
