### ISSUE TITLE
Can't get it to play the text-to-speech

### ISSUE THREAD

**Issue by louis-lau** [Nailik/rhasspy_mobile#331]
Hi! This looks like a really great project, unfortunately I can't get it to work. Maybe I'm not understanding something? I tried following the satellite guide,  and set everything up in the app to connect to my rhasspy server over http. I linked my rhasspy server to home assistant and created an intent script that tells me the temperature.

- Wake work detection works,
- Speech-to-text works and rhasspy displays the text in its interface
- Nothing happens

I then tried setting up the app to communicate with Home assistant directly. Now the intent script is triggered, but then again nothing happens. I can see in the app debug logs it received the speech text from home assistant, but that's all. The audio playing setting is set to local in the app, disabled on my rhasspy server.

Am I completely missing something obvious?

**Comment by Nailik** [comment]
When you say "received the speech text" do you mean the text as text or audio data?
If it's text then the app uses the text-to-speech service to translate it to audio and then plays it.
I am not sure where it hangs, you can open the text-to-speech settings and go on the play arrow and test if it works.

**Comment by bocklucas** [comment]
Hello! I too am experiencing this, I have the app configured to point to my local rhasspy instance, however the logs show nothing when I attempt to submit the requests. Seeing this, ![Screenshot_20230615-220647.png](https://github.com/Nailik/rhasspy_mobile/assets/22528729/1a6d2a7e-b626-4174-87a2-828d742ccff6)

![Screenshot_20230615-220654.png](https://github.com/Nailik/rhasspy_mobile/assets/22528729/fd20b0c7-6405-4946-b703-29084db6aa49)

Any thoughts?

Thanks! Love the project btw 😁

**Comment by Nailik** [comment]
So there is just nothing happening? Could you share your settings?

**Comment by bocklucas** [comment]
Correct yeah, there isnt a call being made to the base station. Absolutely!

Let me know if theres any specific info i can also get,

![Screenshot_20230616-092657.png](https://github.com/Nailik/rhasspy_mobile/assets/22528729/f3dfe061-e3ba-48e2-a069-5b8d8d3cc309)

![Screenshot_20230616-092709.png](https://github.com/Nailik/rhasspy_mobile/assets/22528729/a7e98b61-25a1-420b-8a94-2e152fd4eedf)

![Screenshot_20230616-092749.png](https://github.com/Nailik/rhasspy_mobile/assets/22528729/f343f4db-f878-4f57-b0ea-5e2ab6f97f7e)

![Screenshot_20230616-092805.png](https://github.com/Nailik/rhasspy_mobile/assets/22528729/3e14ce67-252f-4522-8fa7-c96655b9ddff)

![Screenshot_20230616-092827.png](https://github.com/Nailik/rhasspy_mobile/assets/22528729/5852ec40-779a-4380-b799-6840302603c5)

Thanks! 😁

**Comment by Nailik** [comment]
In the settings you can also export them as file so there is no need to make so much screenshots.
Did you also try the prerelease here available on github or which version do you run?

**Comment by bocklucas** [comment]
Oh of course 🙈

![rhasspy_settings_2023-06-16T19_47_27.678.zip](https://github.com/Nailik/rhasspy_mobile/files/11774425/rhasspy_settings_2023-06-16T19_47_27.678.zip)

Im using the current version on Google play

**Comment by Nailik** [comment]
In the test configuration screen there are two buttons in the toolbar (left autoscroll, next to it filter). 
The filter doesn't work perfectly yet, maybe you could disable it and check if you see more information about why it doesn't work.

**Comment by Nailik** [comment]
Should be fixed with the newest release [V_0.5](https://github.com/Nailik/rhasspy_mobile/releases/tag/V_0.5.0-102).
You can consolidate newly updated [Wiki](https://github.com/Nailik/rhasspy_mobile/wiki) for more help.

Mqtt now also supports say endpoint.

Please comment when there are still any issues.
