### ISSUE TITLE
Log says "could not read log file......."

### ISSUE THREAD

**Issue by Doni49** [Nailik/rhasspy_mobile#332]
I have several phones and a tablet running Rhasspy Mobile.  They're all doing this.  

I opened the log file that it did create and this is the contents.

`,{"time":"2023-04-12T13:24:55.350","severity":"Error","tag":"FileLogger","message":"could not read log file","throwable":"Unexpected JSON token at offset 0: Expected start of the array '[', but had '\n' instead at path: $\nJSON input: \n,{\"time\":\"2023-04-12T13:03:43....."}`

![Screenshot_2023-04-12-08-39-56-684](https://user-images.githubusercontent.com/14239245/231476091-3115e6f8-0653-47f2-9653-d1b287894605.jpg)

**Comment by Nailik** [comment]
Hi thanks for the report, this is related to https://github.com/Nailik/rhasspy_mobile/issues/316
The Log Viewer is broken at the moment but you can check out the logs in the App Data Folder
