### ISSUE TITLE
Press microphone icon on screen.  Hear sound.  Then it cancels...

### ISSUE THREAD

**Issue by Doni49** [Nailik/rhasspy_mobile#341]
Quite often, when I press the microphone icon, I'll hear the acknowledgement sound.  Then before I can even speak my request, it'll play the Recorded sound and the microphone changes from the red background back to the blue background.

While troubleshooting this tonight, I had node red open and a debug wired to the Rhasspy trigger (an MQTT node that starts the intent processing).  It never showed that a request was made.

I looked at the log created in the mobile app and it's got a LOT of stuff.

But I'm unsure what to make of it.  This is the contents of the logfile that was created after this time.

`,{"time":"2023-04-23T04:09:20.108","severity":"Debug","tag":"DialogManagerService","message":"onAction WakeWordDetected from Local wakeWord: manual","throwable":null}
,{"time":"2023-04-23T04:09:20.109","severity":"Debug","tag":"IndicationService","message":"onWakeWordDetected","throwable":null}
,{"time":"2023-04-23T04:09:20.109","severity":"Debug","tag":"LocalAudioService","message":"playWakeSound","throwable":null}
,{"time":"2023-04-23T04:09:20.759","severity":"Debug","tag":"DialogManagerService","message":"onAction StartSession from Local","throwable":null}
,{"time":"2023-04-23T04:09:20.760","severity":"Debug","tag":"WakeWordService","message":"stopDetection","throwable":null}
,{"time":"2023-04-23T04:09:20.760","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionStarted from Local","throwable":null}
,{"time":"2023-04-23T04:09:20.761","severity":"Debug","tag":"RecordingService","message":"stopRecording","throwable":null}
,{"time":"2023-04-23T04:09:20.764","severity":"Debug","tag":"DialogManagerService","message":"onAction StartListening from Local sendAudioCaptured: false","throwable":null}
,{"time":"2023-04-23T04:09:20.764","severity":"Debug","tag":"WakeWordService","message":"stopDetection","throwable":null}
,{"time":"2023-04-23T04:09:20.764","severity":"Debug","tag":"IndicationService","message":"onListening","throwable":null}
,{"time":"2023-04-23T04:09:20.765","severity":"Debug","tag":"SpeechToTextService","message":"startSpeechToText sessionId: fa76add9-864f-4f5e-a0ee-ef3ecb17fd6e fromMqtt false","throwable":null}
,{"time":"2023-04-23T04:09:20.774","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:20.774","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:20.774","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:20.775","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionStarted from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:20.775","severity":"Debug","tag":"DialogManagerService","message":"SessionStarted from Mqtt but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:20.781","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/hotword/manual/detected","throwable":null}
,{"time":"2023-04-23T04:09:20.782","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/hotword/manual/detected","throwable":null}
,{"time":"2023-04-23T04:09:20.782","severity":"Debug","tag":"DialogManagerService","message":"onAction WakeWordDetected from Mqtt wakeWord: manual","throwable":null}
,{"time":"2023-04-23T04:09:20.782","severity":"Debug","tag":"IndicationService","message":"onWakeWordDetected","throwable":null}
,{"time":"2023-04-23T04:09:20.782","severity":"Debug","tag":"LocalAudioService","message":"playWakeSound","throwable":null}
,{"time":"2023-04-23T04:09:20.828","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:20.829","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:20.829","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:20.829","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:20.829","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:20.830","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:20.830","severity":"Debug","tag":"DialogManagerService","message":"StartListening from Mqtt sendAudioCaptured: false but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:20.830","severity":"Debug","tag":"DialogManagerService","message":"onAction StartListening from Mqtt sendAudioCaptured: false","throwable":null}
,{"time":"2023-04-23T04:09:20.830","severity":"Debug","tag":"AppSettingsService","message":"hotWordToggle value: false","throwable":null}
,{"time":"2023-04-23T04:09:20.832","severity":"Debug","tag":"RecordingService","message":"startRecording","throwable":null}
,{"time":"2023-04-23T04:09:20.849","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/audioServer/DonPhone/playBytes/f8b7ac0d-f4a8-4bda-b205-4b19d2255c15","throwable":null}
,{"time":"2023-04-23T04:09:20.849","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/audioServer/DonPhone/playBytes/f8b7ac0d-f4a8-4bda-b205-4b19d2255c15","throwable":null}
,{"time":"2023-04-23T04:09:20.849","severity":"Debug","tag":"DialogManagerService","message":"onAction PlayAudio from Mqtt size: 83948","throwable":null}
,{"time":"2023-04-23T04:09:20.849","severity":"Debug","tag":"LocalAudioService","message":"stop","throwable":null}
,{"time":"2023-04-23T04:09:20.849","severity":"Debug","tag":"IndicationService","message":"onPlayAudio","throwable":null}
,{"time":"2023-04-23T04:09:20.850","severity":"Debug","tag":"AudioPlayingService","message":"playAudio dataSize: 83948","throwable":null}
,{"time":"2023-04-23T04:09:20.850","severity":"Debug","tag":"LocalAudioService","message":"playAudio 83948","throwable":null}
,{"time":"2023-04-23T04:09:21.319","severity":"Debug","tag":"DialogManagerService","message":"onAction StartSession from Local","throwable":null}
,{"time":"2023-04-23T04:09:21.320","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionStarted from Local","throwable":null}
,{"time":"2023-04-23T04:09:21.319","severity":"Debug","tag":"WakeWordService","message":"stopDetection","throwable":null}
,{"time":"2023-04-23T04:09:21.322","severity":"Debug","tag":"DialogManagerService","message":"onAction StartListening from Local sendAudioCaptured: false","throwable":null}
,{"time":"2023-04-23T04:09:21.322","severity":"Debug","tag":"WakeWordService","message":"stopDetection","throwable":null}
,{"time":"2023-04-23T04:09:21.322","severity":"Debug","tag":"IndicationService","message":"onListening","throwable":null}
,{"time":"2023-04-23T04:09:21.323","severity":"Debug","tag":"SpeechToTextService","message":"startSpeechToText sessionId: 4cc6fed7-3292-4f9e-89d2-dc1248391d2d fromMqtt false","throwable":null}
,{"time":"2023-04-23T04:09:21.326","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:21.327","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:21.327","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:21.328","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionStarted from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:21.328","severity":"Debug","tag":"DialogManagerService","message":"SessionStarted from Mqtt but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:21.378","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:21.378","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:21.379","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:21.379","severity":"Debug","tag":"MqttService","message":"isNotThisSiteId mqttTopic notFound hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:21.388","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:21.388","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:21.388","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:21.389","severity":"Debug","tag":"MqttService","message":"isNotThisSiteId mqttTopic notFound hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:21.552","severity":"Debug","tag":"LocalAudioService","message":"onFinished","throwable":null}
,{"time":"2023-04-23T04:09:21.553","severity":"Debug","tag":"DialogManagerService","message":"onAction PlayFinished from Local","throwable":null}
,{"time":"2023-04-23T04:09:21.553","severity":"Debug","tag":"IndicationService","message":"onListening","throwable":null}
,{"time":"2023-04-23T04:09:21.594","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/audioServer/DonPhone/playFinished","throwable":null}
,{"time":"2023-04-23T04:09:21.595","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/audioServer/DonPhone/playFinished","throwable":null}
,{"time":"2023-04-23T04:09:21.595","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/audioServer/DonPhone/playFinished","throwable":null}
,{"time":"2023-04-23T04:09:21.596","severity":"Debug","tag":"DialogManagerService","message":"onAction PlayFinished from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:21.596","severity":"Debug","tag":"IndicationService","message":"onListening","throwable":null}
,{"time":"2023-04-23T04:09:22.079","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:22.078","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:22.080","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:22.080","severity":"Debug","tag":"AppSettingsService","message":"hotWordToggle value: true","throwable":null}
,{"time":"2023-04-23T04:09:22.138","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:22.139","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:22.139","severity":"Debug","tag":"AppSettingsService","message":"hotWordToggle value: false","throwable":null}
,{"time":"2023-04-23T04:09:22.139","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:22.140","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:22.140","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:22.140","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:22.140","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:22.140","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/dialogueManager/sessionStarted","throwable":null}
,{"time":"2023-04-23T04:09:22.140","severity":"Debug","tag":"DialogManagerService","message":"SessionStarted from Mqtt but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:22.141","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionStarted from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:22.140","severity":"Debug","tag":"DialogManagerService","message":"StartListening from Mqtt sendAudioCaptured: true but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:22.141","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/asr/startListening","throwable":null}
,{"time":"2023-04-23T04:09:22.141","severity":"Debug","tag":"DialogManagerService","message":"onAction StartListening from Mqtt sendAudioCaptured: true","throwable":null}
,{"time":"2023-04-23T04:09:23.247","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/asr/textCaptured","throwable":null}
,{"time":"2023-04-23T04:09:23.247","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/asr/textCaptured","throwable":null}
,{"time":"2023-04-23T04:09:23.248","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/asr/textCaptured","throwable":null}
,{"time":"2023-04-23T04:09:23.250","severity":"Debug","tag":"DialogManagerService","message":"onAction AsrTextCaptured from Mqtt text: ","throwable":null}
,{"time":"2023-04-23T04:09:23.251","severity":"Debug","tag":"SpeechToTextService","message":"endSpeechToText sessionId: 4cc6fed7-3292-4f9e-89d2-dc1248391d2d fromMqtt true","throwable":null}
,{"time":"2023-04-23T04:09:23.251","severity":"Debug","tag":"IndicationService","message":"onRecognizingIntent","throwable":null}
,{"time":"2023-04-23T04:09:23.251","severity":"Debug","tag":"IntentRecognitionService","message":"recognizeIntent sessionId: 4cc6fed7-3292-4f9e-89d2-dc1248391d2d text: ","throwable":null}
,{"time":"2023-04-23T04:09:23.252","severity":"Debug","tag":"RecordingService","message":"stopRecording","throwable":null}
,{"time":"2023-04-23T04:09:23.264","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:23.265","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:23.265","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:23.265","severity":"Debug","tag":"MqttService","message":"isNotThisSiteId mqttTopic notFound hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:23.318","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/nlu/intentNotRecognized","throwable":null}
,{"time":"2023-04-23T04:09:23.318","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/nlu/intentNotRecognized","throwable":null}
,{"time":"2023-04-23T04:09:23.318","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/nlu/intentNotRecognized","throwable":null}
,{"time":"2023-04-23T04:09:23.319","severity":"Debug","tag":"DialogManagerService","message":"onAction IntentRecognitionError from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:23.319","severity":"Debug","tag":"IndicationService","message":"onError","throwable":null}
,{"time":"2023-04-23T04:09:23.319","severity":"Debug","tag":"LocalAudioService","message":"playErrorSound","throwable":null}
,{"time":"2023-04-23T04:09:23.340","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionEnded from Local","throwable":null}
,{"time":"2023-04-23T04:09:23.340","severity":"Debug","tag":"IndicationService","message":"onIdle","throwable":null}
,{"time":"2023-04-23T04:09:23.341","severity":"Debug","tag":"RecordingService","message":"startRecording","throwable":null}
,{"time":"2023-04-23T04:09:23.344","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:23.344","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:23.344","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/hotword/toggleOff","throwable":null}
,{"time":"2023-04-23T04:09:23.345","severity":"Debug","tag":"AppSettingsService","message":"hotWordToggle value: false","throwable":null}
,{"time":"2023-04-23T04:09:23.375","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/audioServer/DonPhone/playBytes/92c813b4-438e-4379-a3b3-2af22be4caf3","throwable":null}
,{"time":"2023-04-23T04:09:23.376","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/audioServer/DonPhone/playBytes/92c813b4-438e-4379-a3b3-2af22be4caf3","throwable":null}
,{"time":"2023-04-23T04:09:23.376","severity":"Debug","tag":"DialogManagerService","message":"onAction PlayAudio from Mqtt size: 155492","throwable":null}
,{"time":"2023-04-23T04:09:23.376","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:23.376","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:23.377","severity":"Debug","tag":"IndicationService","message":"onPlayAudio","throwable":null}
,{"time":"2023-04-23T04:09:23.377","severity":"Debug","tag":"LocalAudioService","message":"stop","throwable":null}
,{"time":"2023-04-23T04:09:23.377","severity":"Debug","tag":"DialogManagerService","message":"SessionEnded from Mqtt but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:23.377","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionEnded from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:23.379","severity":"Debug","tag":"AudioPlayingService","message":"playAudio dataSize: 155492","throwable":null}
,{"time":"2023-04-23T04:09:23.379","severity":"Debug","tag":"LocalAudioService","message":"playAudio 155492","throwable":null}
,{"time":"2023-04-23T04:09:23.375","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:24.428","severity":"Debug","tag":"LocalAudioService","message":"onFinished","throwable":null}
,{"time":"2023-04-23T04:09:24.428","severity":"Debug","tag":"DialogManagerService","message":"onAction PlayFinished from Local","throwable":null}
,{"time":"2023-04-23T04:09:24.429","severity":"Debug","tag":"IndicationService","message":"onIdle","throwable":null}
,{"time":"2023-04-23T04:09:24.440","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/audioServer/DonPhone/playFinished","throwable":null}
,{"time":"2023-04-23T04:09:24.441","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/audioServer/DonPhone/playFinished","throwable":null}
,{"time":"2023-04-23T04:09:24.441","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/audioServer/DonPhone/playFinished","throwable":null}
,{"time":"2023-04-23T04:09:24.441","severity":"Debug","tag":"DialogManagerService","message":"onAction PlayFinished from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:24.441","severity":"Debug","tag":"IndicationService","message":"onIdle","throwable":null}
,{"time":"2023-04-23T04:09:25.363","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:25.364","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:25.364","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:25.365","severity":"Debug","tag":"AppSettingsService","message":"hotWordToggle value: true","throwable":null}
,{"time":"2023-04-23T04:09:30.768","severity":"Debug","tag":"DialogManagerService","message":"StopListening from Local called in wrong state AwaitingWakeWord expected one of RecordingIntent","throwable":null}
,{"time":"2023-04-23T04:09:30.767","severity":"Debug","tag":"DialogManagerService","message":"onAction StopListening from Local","throwable":null}
,{"time":"2023-04-23T04:09:30.766","severity":"Debug","tag":"DialogManagerService","message":"recordingTimeout","throwable":null}
,{"time":"2023-04-23T04:09:52.099","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/asr/stopListening","throwable":null}
,{"time":"2023-04-23T04:09:52.097","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/asr/stopListening","throwable":null}
,{"time":"2023-04-23T04:09:52.098","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/asr/stopListening","throwable":null}
,{"time":"2023-04-23T04:09:52.109","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:52.113","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:52.113","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:52.114","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/dialogueManager/sessionEnded","throwable":null}
,{"time":"2023-04-23T04:09:52.115","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:52.116","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/hotword/toggleOn","throwable":null}
,{"time":"2023-04-23T04:09:52.119","severity":"Debug","tag":"AppSettingsService","message":"hotWordToggle value: true","throwable":null}
,{"time":"2023-04-23T04:09:52.121","severity":"Debug","tag":"DialogManagerService","message":"onAction StopListening from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:52.121","severity":"Debug","tag":"DialogManagerService","message":"StopListening from Mqtt but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:52.122","severity":"Debug","tag":"DialogManagerService","message":"onAction SessionEnded from Mqtt","throwable":null}
,{"time":"2023-04-23T04:09:52.122","severity":"Debug","tag":"DialogManagerService","message":"SessionEnded from Mqtt but local dialog management","throwable":null}
,{"time":"2023-04-23T04:09:52.159","severity":"Debug","tag":"MqttService","message":"onMessageReceived id 0 hermes/asr/textCaptured","throwable":null}
,{"time":"2023-04-23T04:09:52.164","severity":"Debug","tag":"MqttService","message":"regexTopic hermes/asr/textCaptured","throwable":null}
,{"time":"2023-04-23T04:09:52.166","severity":"Debug","tag":"MqttService","message":"compareTopic hermes/asr/textCaptured","throwable":null}
,{"time":"2023-04-23T04:09:52.175","severity":"Debug","tag":"DialogManagerService","message":"onAction AsrTextCaptured from Mqtt text: what time is it","throwable":null}
,{"time":"2023-04-23T04:09:52.177","severity":"Debug","tag":"DialogManagerService","message":"AsrTextCaptured from Mqtt text: what time is it called in wrong state AwaitingWakeWord expected one of TranscribingIntent, RecordingIntent","throwable":null}`

**Comment by Nailik** [comment]
It looks like `asrTextCaptured` is triggered with an empty text from the base.
This seems to happen to a various number of people but i have to debug why this happens.

**Comment by Nailik** [comment]
I found probably finally found the issue.
When recording is started the first buffer might contain mostly zeros and therefore rhasspy detects silence and tries to parse the audio. Because it's pretty much empty it just stops and results in  `asrTextCaptured` with empty text.

I'll fix this in https://github.com/Nailik/rhasspy_mobile/issues/370

**Comment by Nailik** [comment]
Should be fixed with the newest release [V_0.5](https://github.com/Nailik/rhasspy_mobile/releases/tag/V_0.5.0-102).
You can consolidate newly updated [Wiki](https://github.com/Nailik/rhasspy_mobile/wiki) for more help.

Please comment when there are still any issues.
