### ISSUE TITLE
Initiate a session on one and multiple devices play the acknowledgement sound....

### ISSUE THREAD

**Issue by Doni49** [Nailik/rhasspy_mobile#342]
I have 6 phones running Rhasspy Mobile.  I've noticed that when ONE starts recording (even a manual recording started by pressing the big microphone button), multiple devices play the acknowledgement sound and start recording.  But when this happens NOTHING is sent to the server.

I haven't figured out what it's doing in those cases where it'll the request does make it to the server.

See the following short video (less than 2 Min long).
[https://youtu.be/RCWBrzMRSBg](https://youtu.be/RCWBrzMRSBg)

**Comment by Doni49** [comment]
I suspect this is probably linked to the other issue I raised a few minutes ago.  I only just now realized they're probably related.

[https://github.com/Nailik/rhasspy_mobile/issues/341#issue-1679850998](https://github.com/Nailik/rhasspy_mobile/issues/341#issue-1679850998)

**Comment by Nailik** [comment]
Please check that your devices have different siteIds.

When you have Mqtt enabled and press the Microphone action it will publish a message to `hermes/hotword/<wakeWordId>/detected` with the `siteId` of the device. When another device has the same `siteId` it may react to this message.

**Comment by Doni49** [comment]
> Please check that your devices have different siteIds.
> 
> When you have Mqtt enabled and press the Microphone action it will publish a message to `hermes/hotword/<wakeWordId>/detected` with the `siteId` of the device. When another device has the same `siteId` it may react to this message.

Confirmed every satellite has its own unique site ID.  And this is what's entered in the SiteIDs field within the wake work portion (it's copy(pasted into every one of those fields actually) of the Rhasspy server's WebUI:  bedroom,DonPhone,kitchen,garage,office,bathroom

**Comment by Nailik** [comment]
Please test if this issue still exists with the newest release [V_0.5](https://github.com/Nailik/rhasspy_mobile/releases/tag/V_0.5.0-102).
You can consolidate newly updated [Wiki](https://github.com/Nailik/rhasspy_mobile/wiki) for more help.

**Comment by Nailik** [comment]
I was finally able to identify the bugs.
for the `hermes/hotword/<wakeWordId>/detected` the siteId was ignored (maybe due to how udp wakeword works)
This bug here will be fixed soon but first i have to check that i don't brake udp wakeword.

**Comment by Nailik** [comment]
will be fixed with https://github.com/Nailik/rhasspy_mobile/issues/442
