### ISSUE TITLE
Porcupine custom wake-words result in Error: invalid argument exception

### ISSUE THREAD

**Issue by kcognata** [Nailik/rhasspy_mobile#350]
First off, wanted to say I love what you've done and this app is amazing. Great work!

**Story:**
I've been having an issue getting a custom wake-word .ppn files to work at all. 

**Steps to reproduce:**
After selecting the file and going back to the wake-word page, I get an red error bar at the top of the app. 
If I click it it says "invalid argument exception". 
If I continue to go back to the main configurations page (and click save) the error bar persists and now doesn't say anything when I click it.

I've tried exporting the custom wake word where the Platform was "Android" as well as "Web". I tried importing the .ppn files after they were exported from the .zip file, as well as the entire .zip file. All methods resulted in the same error. Once in this error state, audio detection fails to work even after removing the custom wake-word. Device requires reboot to get things working again with non-custom wake-words.

**Configuration Info:**
I'm on a Samsung Galaxy Tab A. I'm using Porcupine for wake word detection.

**Comment by Nailik** [comment]
Thanks for checking out the project and filing the issue.
I think you may have created a custom wakeword for porcupine version 2.2 and it's not compatible with the app which uses 2.1 - related to https://github.com/Nailik/rhasspy_mobile/issues/351 .
In the next update it will be updated to 2.2 (just some more testing is necessary).
