### ISSUE TITLE
How to get latest development build?

### ISSUE THREAD

**Issue by bj00rn** [Nailik/rhasspy_mobile#371]
How do I get the latest built apks for the project from develop? 

Maybe worth a mention in README.MD..

Thanks!

**Comment by bj00rn** [comment]
> Either by downloading from the Releases tab https://github.com/Nailik/rhasspy_mobile/releases/tag/V_0.4.9-66 or from the playstore https://play.google.com/store/apps/details?id=org.rhasspy.mobile.android
> 
> You can also build it by yourself. To build a release version you need to create your own android keystore and fill out https://github.com/Nailik/rhasspy_mobile/blob/develop/signing.properties.example

If I want the latest build from source i mean. Something like `nightly build` or the sorts. Had a look under actions and downloaded the built apks from the last PR seems to work.

**Comment by bj00rn** [comment]
I'm just shooting ideas here, isn't it possible to have a build action on merge/commit to develop (or cron based) to carve a nightly release?

I have limited experience with pipelines, and maybe this isn't actually an issue and not worth looking into. 

Cheers!

**Comment by Nailik** [comment]
jeah i already build dev on merge in develop so i think uploading this to a nightly release should be easy

**Comment by Nailik** [comment]
The builds can now be found in the nightly release https://github.com/Nailik/rhasspy_mobile/releases/tag/nightly

**Comment by bj00rn** [comment]
> The builds can now be found in the nightly release https://github.com/Nailik/rhasspy_mobile/releases/tag/nightly

Awesome! Will give it a try!
