### ISSUE TITLE
Duplicate strings

### ISSUE THREAD

**Issue by bj00rn** [Nailik/rhasspy_mobile#374]
Duplicate strings here (386-392), looks like copy paste mistake.

(Default string for logSettings is in german as a result)

https://github.com/Nailik/rhasspy_mobile/blob/28e0689441b128c89d27c961b39dfb5c163f4f6a/resources/src/commonMain/resources/MR/base/strings.xml#L386-L392

**Comment by Nailik** [comment]
Thanks, that's already fixed in the current dev but i just realized that the english translation is messed up and shows the german text.
