### ISSUE TITLE
Cannot exit dialog when testing TTS, close (x) button does nothing

### ISSUE THREAD

**Issue by bj00rn** [Nailik/rhasspy_mobile#383]
Cannot exit TTS test. 
- (x) button does not close dialog
- back action not working either
Reproduce
1. Under TTS settings
2. Click play icon
3. Click (x) button on top left

**Comment by Nailik** [comment]
this is theoretically fixed with https://github.com/Nailik/rhasspy_mobile/pull/385 but for now the testing possibility is removed and will come back later on

**Comment by Nailik** [comment]
With https://github.com/Nailik/rhasspy_mobile/pull/394 there is now a simpler way to test the configuration by viewing the history (max 100 states and what action caused them) of the dialog.

Also the code of the configuration pages was completely renewed with https://github.com/Nailik/rhasspy_mobile/pull/385
