### ISSUE TITLE
Silence Detection

### ISSUE THREAD

**Issue by arturpragacz** [Nailik/rhasspy_mobile#391]
I cannot get automatic silence detection to work correctly. Even though I have it set up for 2s silence detection time, it takes significantly longer than that to activate. Oftentimes it does not activate at all.
Even when I set audio level threshold to some absurdly high value for testing, it does not activate in the time it should.

**Comment by Nailik** [comment]
which version are you using and what device, also android version would be interesting

**Comment by Nailik** [comment]
jeah the broadcast is broken in the current nightly build.
I'll check the problem and come back to you later.

**Comment by Nailik** [comment]
@arturpragacz  about the broadcast i updated the readme, it change minimally see https://github.com/Nailik/rhasspy_mobile/pull/397 .

**Comment by arturpragacz** [comment]
Great!
Have you had a chance to look into the silence detection issue as well?

**Comment by Nailik** [comment]
Jeah there is at least one bug where the minimum recording time is completely ignored.
I rewrote the thing and currently implement unit tests for it so i can be sure it works as expected.

**Comment by Nailik** [comment]
@arturpragacz there is now a new nightly build available, i would be very happy if you could try it out and tell me if there are still issues for you
