### ISSUE TITLE
Wake word "pending" on latest update

### ISSUE THREAD

**Issue by undrwater** [Nailik/rhasspy_mobile#431]
The previous version worked well. Currently on nightly, and wake word reports "pending" regardless of local (porcupine) or udp audio (my setup is udp, though I do have a key for porcupine).

**Comment by undrwater** [comment]
I'd like to add a log, but I can't seem to figure how to add an attachment.

**Comment by Nailik** [comment]
I just checked and pending might be misleading but when Microphone permission is missing it will show pending.
Under WakeWord -> udp there should be a button "allow microphone permission" you could also simply click on the microphone button on the start screen.

**Comment by undrwater** [comment]
Microphone permission has been granted, yet the problem persists.

Truly appreciate your work on this project.

**Comment by Nailik** [comment]
To further investage i would need to know the settings of the app (can be exported) as well as the log.
When writing a comment you can attach files by dragging & dropping them below them comment section.

**Comment by undrwater** [comment]
[org.rhasspy.mobile.android_preferences_export.tar.gz](https://github.com/Nailik/rhasspy_mobile/files/12306203/org.rhasspy.mobile.android_preferences_export.tar.gz)
[rhasspy_logfile_2023-08-09T19_23_18.812.tar.gz](https://github.com/Nailik/rhasspy_mobile/files/12306226/rhasspy_logfile_2023-08-09T19_23_18.812.tar.gz)

**Comment by Nailik** [comment]
Ahh i see DialogManagementOption is set to Disabled and that does currently not initially start the WakeWordService - that's a flaw in the code from my side.

**Comment by Nailik** [comment]
Will be fixed with https://github.com/Nailik/rhasspy_mobile/issues/437

**Comment by Nailik** [comment]
But i am curious how do you use the app with DialogManagementOption Disabled?

**Comment by undrwater** [comment]
Right now while I have it enabled, there are 3 response tones before listening for the command happens.

IIRC with it disabled, there is just the one tone, and response time is much quicker.
