### ISSUE TITLE
No local sound on Fire HD after MQTT response

### ISSUE THREAD

**Issue by bytedealer** [Nailik/rhasspy_mobile#525]
Hi @Nailik,

great work! I am using Rhasspy 2.5.11 on a server and had a server-satellite system already running with a Synology as base and a RPI as satellite. But the idea with a table is genious. 

So I use a Fire HD 10 from 2021. Everything is fine but the text of the hermes/dialogueManager/endSession is not spoken, so no sound or audio. It does not matter if I use sound or notification.

Here is the response to hermes/dialogueManager/endSession:
`{
  "text" : "Okay!",
  "lang" : "de",
  "sessionId" : "c12a137a-8d2c-4da7-8557-5fc8ec0d3f30"
}`

Do you have an idea what is wrong?

Thanks in advance!
bytedealer

**Comment by Nailik** [comment]
I think you need to send the text via text-to-speech request. 
The test inside EndSession is currently not used.

**Comment by bytedealer** [comment]
Hey @Nailik!

Thank you for your fast response! I think you mean hermes/tts/say, right?

I will try later and give feedback.

Have a good one!
bytedealer

**Comment by Nailik** [comment]
Yes exactly. The app will then use the defined server to translate it and speak it over the defined audio output.

**Comment by bytedealer** [comment]
Mission accomplished. Sound is spoken with hermes/tts/say.

Thank you for your help!
Issue can be closed.

Bye
bytedealer
