### ISSUE TITLE
Porcupine custom WakeWord v3

### ISSUE THREAD

**Issue by juliend20** [Nailik/rhasspy_mobile#531]
I tried to use custom WakeWord from picovoice.ai but the ppn file generated by the server is in version 3.

Can you update the library porcupine in this app to v3 ?

**Comment by Nailik** [comment]
porcupine is currently version 3 on nightly - could you try it with this version?

**Comment by juliend20** [comment]
Ok I tested with the ppn v3 it's work well, You just need to replace (2.2.2) by (3) in the message "All active activation words.... with the current Porcupine version (2.2.2)!".

**Comment by Nailik** [comment]
ahh thanks

**Comment by juliend20** [comment]
Thanks
